name: "trab-final-frameworks"

services:
  pg:
    image: bitnami/postgresql:16.4.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=trab-final-frameworks
    volumes:
      - 'db:/var/lib/postgresql/data'

volumes:
  db:
    driver: local